# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Qingchuan-Ma'Blog
paginate:       3
baseurl:        ""
url:            "https://Qingchuan-Ma.github.io/blog"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown
textile_ext:    textile

# About
author:
  name:         Qingchuan Ma
  url:          https://github.com/Qingchuan-Ma
  email:        1600011621@pku.edu.cn

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/Qingchuan-Ma/blog

# Gems
plugins: [jekyll-paginate]
